In [1]:
import numpy as np
import pandas as pd
#import os
#import matplotlib.pyplot as plt
#%matplotlib inline

In [3]:
titanic_train = pd.read_csv("E:/Machine Learning/Machine-Learning-Masters-master/Machine-Learning-Masters-master/ML (Support Material)/ML/9_decision_tree/Exercise/titanic.csv")    
titanic_train.head(20)
titanic_train.style.highlight_null(null_color='red')

Bad key "text.kerning_factor" on line 4 in
C:\Users\91920\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.1.3/matplotlibrc.template
or from the matplotlib source distribution

# titanic_train.style.highlight_null(null_color='red')

# pd.set_option('display.max_rows', None)
titanic_train

In [17]:
titanic_train.tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [19]:
titanic_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [13]:
sum(titanic_train.isnull().sum())

866

In [6]:
titanic_train.describe() #only of numerical data

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,156.000000,156.000000,156.000000,126.000000,156.000000,156.000000,156.000000
mean,78.500000,0.346154,2.423077,28.141508,0.615385,0.397436,28.109587
std,45.177428,0.477275,0.795459,14.613880,1.056235,0.870146,39.401047
min,1.000000,0.000000,1.000000,0.830000,0.000000,0.000000,6.750000
25%,39.750000,0.000000,2.000000,19.000000,0.000000,0.000000,8.003150
50%,78.500000,0.000000,3.000000,26.000000,0.000000,0.000000,14.454200
75%,117.250000,1.000000,3.000000,35.000000,1.000000,0.000000,30.371850
max,156.000000,1.000000,3.000000,71.000000,5.000000,5.000000,263.000000

In [17]:
titanic_train['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [6]:
titanic_train.dtypes[titanic_train.dtypes == "object"]

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [15]:
titanic_train.dtypes == "object"

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [18]:
a=titanic_train.dtypes[titanic_train.dtypes == "object"]
print(a)

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [18]:
a.describe()

count          5
unique         1
top       object
freq           5
dtype: object

In [101]:
titanic_train.dtypes[titanic_train.dtypes == "object"].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [103]:
list_col = titanic_train.dtypes[titanic_train.dtypes == "object"].index
titanic_train[list_col].describe()

                                Name   Sex  Ticket Cabin Embarked
count                            156   156     156    31      155
unique                           156     2     145    28        3
top     Williams, Mr. Charles Eugene  male  113803  C123        S
freq                               1   100       2     2      110

In [163]:
#now for categorical column
titanic_train.dtypes == "object"
a = titanic_train.dtypes[titanic_train.dtypes == "object"].index
a
titanic_train[a].describe()

                                Name   Sex  Ticket Cabin Embarked
count                            156   156     156    31      155
unique                           156     2     145    28        3
top     Williams, Mr. Charles Eugene  male  113803  C123        S
freq                               1   100       2     2      110

In [4]:
titanic_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Name         156 non-null    object
 4   Sex          156 non-null    object
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64
 7   Parch        156 non-null    int64
 8   Ticket       156 non-null    object
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     object
 11  Embarked     155 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 14.8+ KB

In [6]:
titanic_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [110]:
titanic_train[['Name','Sex','Age']]

                                                  Name     Sex   Age
0                              Braund, Mr. Owen Harris    male  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                               Heikkinen, Miss. Laina  female  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                             Allen, Mr. William Henry    male  35.0
5                                     Moran, Mr. James    male   NaN
6                              McCarthy, Mr. Timothy J    male  54.0
7                       Palsson, Master. Gosta Leonard    male   2.0
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0
10                     Sandstrom, Miss. Marguerite Rut  female   4.0
11                            Bonnell, Miss. Elizabeth  female  58.0
12                      Saundercock, Mr. William Henry    male  20.0
13                         Andersson, Mr. Anders Johan    male  39.0
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0
16                                Rice, Master. Eugene    male   2.0
17                        Williams, Mr. Charles Eugene    male   NaN
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0
19                             Masselmani, Mrs. Fatima  female   NaN
20                                Fynney, Mr. Joseph J    male  35.0
21                               Beesley, Mr. Lawrence    male  34.0
22                         McGowan, Miss. Anna "Annie"  female  15.0
23                        Sloper, Mr. William Thompson    male  28.0
24                       Palsson, Miss. Torborg Danira  female   8.0
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.0
26                             Emir, Mr. Farred Chehab    male   NaN
27                      Fortune, Mr. Charles Alexander    male  19.0
28                       O'Dwyer, Miss. Ellen "Nellie"  female   NaN
29                                 Todoroff, Mr. Lalio    male   NaN
..                                                 ...     ...   ...
126                                McMahon, Mr. Martin    male   NaN
127                          Madsen, Mr. Fridtjof Arne    male  24.0
128                                  Peter, Miss. Anna  female   NaN
129                                 Ekstrom, Mr. Johan    male  45.0
130                               Drazenoic, Mr. Jozef    male  33.0
131                     Coelho, Mr. Domingos Fernandeo    male  20.0
132     Robins, Mrs. Alexander A (Grace Charity Laury)  female  47.0
133      Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0
134                     Sobey, Mr. Samuel James Hayden    male  25.0
135                                 Richard, Mr. Emile    male  23.0
136                       Newsom, Miss. Helen Monypeny  female  19.0
137                        Futrelle, Mr. Jacques Heath    male  37.0
138                                Osen, Mr. Olaf Elon    male  16.0
139                                 Giglio, Mr. Victor    male  24.0
140                      Boulos, Mrs. Joseph (Sultana)  female   NaN
141                           Nysten, Miss. Anna Sofia  female  22.0
142  Hakkarainen, Mrs. Pekka Pietari (Elin Matilda ...  female  24.0
143                                Burke, Mr. Jeremiah    male  19.0
144                         Andrew, Mr. Edgardo Samuel    male  18.0
145                       Nicholls, Mr. Joseph Charles    male  19.0
146       Andersson, Mr. August Edvard ("Wennerstrom")    male  27.0
147                   Ford, Miss. Robina Maggie "Ruby"  female   9.0
148           Navratil, Mr. Michel ("Louis M Hoffman")    male  36.5
149                  Byles, Rev. Thomas Roussel Davids    male  42.0
150                         Bateman, Rev. Robert James    male  51.0
151                  Pears, Mrs. Thomas (Edith Wearne)  female  22.0
152                                   Meo, Mr. Alfonzo    male  55.5
153                    van Billiard, Mr. Austin Blyler    male  40.5
154                              Olsen, Mr. Ole Martin    male   NaN
155                        Williams, Mr. Charles Duane    male  51.0

[156 rows x 3 columns]

In [166]:
sorted(titanic_train["Name"])[5 :10:2]# Check the first 15 sorted names

['Andersson, Mr. August Edvard ("Wennerstrom")',
 'Andrew, Mr. Edgardo Samuel',
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)']

In [167]:
titanic_train["Name"].describe()

count                              156
unique                             156
top       Williams, Mr. Charles Eugene
freq                                 1
Name: Name, dtype: object

In [168]:
titanic_train[["Ticket"]][4:9]  #operation on df as [['ticket']]

   Ticket
4  373450
5  330877
6   17463
7  349909
8  347742

In [169]:
titanic_train["Ticket"].describe()
titanic_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [171]:
titanic_train["sudh"]="sdffs"
titanic_train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,test,sudh
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,sdffs
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,sdffs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,sdffs
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0,sdffs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,sdffs

In [172]:
titanic_train["Cabin"][0:15]       # Check the first 15 tickets

0      NaN
1      C85
2      NaN
3     C123
4      NaN
5      NaN
6      E46
7      NaN
8      NaN
9      NaN
10      G6
11    C103
12     NaN
13     NaN
14     NaN
Name: Cabin, dtype: object

In [118]:
titanic_train.dtypes# Check number of unique cabins

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
test             int64
dtype: object

In [26]:
titanic_train[titanic_train["Survived"]==1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.00,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.00,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.00,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.00,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.00,0,0,113783,26.5500,C103,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.00,0,0,248706,16.0000,NaN,S
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
21,22,1,2,"Beesley, Mr. Lawrence",male,34.00,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.00,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.00,0,0,113788,35.5000,A6,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.00,1,5,347077,31.3875,NaN,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
32,33,1,3,"Glynn, Miss. Mary Agatha",female,NaN,0,0,335677,7.7500,NaN,Q
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.00,1,0,2651,11.2417,NaN,C
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
44,45,1,3,"Devaney, Miss. Margaret Delia",female,19.00,0,0,330958,7.8792,NaN,Q
47,48,1,3,"O'Driscoll, Miss. Bridget",female,NaN,0,0,14311,7.7500,NaN,Q
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.00,1,0,PC 17572,76.7292,D33,C
53,54,1,2,"Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...",female,29.00,1,0,2926,26.0000,NaN,S
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
56,57,1,2,"Rugg, Miss. Emily",female,21.00,0,0,C.A. 31026,10.5000,NaN,S
58,59,1,2,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,27.7500,NaN,S
61,62,1,1,"Icard, Miss. Amelie",female,38.00,0,0,113572,80.0000,B28,NaN
65,66,1,3,"Moubarek, Master. Gerios",male,NaN,1,1,2661,15.2458,NaN,C
66,67,1,2,"Nye, Mrs. (Elizabeth Ramell)",female,29.00,0,0,C.A. 29395,10.5000,F33,S
68,69,1,3,"Andersson, Miss. Erna Alexandra",female,17.00,4,2,3101281,7.9250,NaN,S
74,75,1,3,"Bing, Mr. Lee",male,32.00,0,0,1601,56.4958,NaN,S
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
79,80,1,3,"Dowdell, Miss. Elizabeth",female,30.00,0,0,364516,12.4750,NaN,S
81,82,1,3,"Sheerlinck, Mr. Jan Baptist",male,29.00,0,0,345779,9.5000,NaN,S
82,83,1,3,"McDermott, Miss. Brigdet Delia",female,NaN,0,0,330932,7.7875,NaN,Q
84,85,1,2,"Ilett, Miss. Bertha",female,17.00,0,0,SO/C 14885,10.5000,NaN,S
85,86,1,3,"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...",female,33.00,3,0,3101278,15.8500,NaN,S
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.00,3,2,19950,263.0000,C23 C25 C27,S
97,98,1,1,"Greenfield, Mr. William Bertram",male,23.00,0,1,PC 17759,63.3583,D10 D12,C
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.00,0,1,231919,23.0000,NaN,S
106,107,1,3,"Salkjelsvik, Miss. Anna Kristine",female,21.00,0,0,343120,7.6500,NaN,S
107,108,1,3,"Moss, Mr. Albert Johan",male,NaN,0,0,312991,7.7750,NaN,S
109,110,1,3,"Moran, Miss. Bertha",female,NaN,1,0,371110,24.1500,NaN,Q
123,124,1,2,"Webber, Miss. Susan",female,32.50,0,0,27267,13.0000,E101,S
125,126,1,3,"Nicola-Yarred, Master. Elias",male,12.00,1,0,2651,11.2417,NaN,C
127,128,1,3,"Madsen, Mr. Fridtjof Arne",male,24.00,0,0,C 17369,7.1417,NaN,S
128,129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
133,134,1,2,"Weisz, Mrs. Leopold (Mathilde Francoise Pede)",female,29.00,1,0,228414,26.0000,NaN,S
136,137,1,1,"Newsom, Miss. Helen Monypeny",female,19.00,0,2,11752,26.2833,D47,S
141,142,1,3,"Nysten, Miss. Anna Sofia",female,22.00,0,0,347081,7.7500,NaN,S
142,143,1,3,"Hakkarainen, Mrs. Pekka Pietari (Elin Matilda ...",female,24.00,1,0,STON/O2. 3101279,15.8500,NaN,S
146,147,1,3,"Andersson, Mr. August Edvard (""Wennerstrom"")",male,27.00,0,0,350043,7.7958,NaN,S
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.00,1,0,113776,66.6000,C2,S
156,157,1,3,"Gilnagh, Miss. Katherine ""Katie""",female,16.00,0,0,35851,7.7333,NaN,Q
161,162,1,2,"Watt, Mrs. James (Elizabeth ""Bessie"" Inglis Mi...",female,40.00,0,0,C.A. 33595,15.7500,NaN,S
165,166,1,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9.00,0,2,363291,20.5250,NaN,S
166,167,1,1,"Chibnall, Mrs. (Edith Martha Bowerman)",female,NaN,0,1,113505,55.0000,E33,S
172,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.00,1,1,347742,11.1333,NaN,S
183,184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,F4,S
184,185,1,3,"Kink-Heilmann, Miss. Luise Gretchen",female,4.00,0,2,315153,22.0250,NaN,S
186,187,1,3,"O'Brien, Mrs. Thomas (Johanna ""Hannah"" Godfrey)",female,NaN,1,0,370365,15.5000,NaN,Q
187,188,1,1,"Romaine, Mr. Charles Hallace (""Mr C Rolmane"")",male,45.00,0,0,111428,26.5500,NaN,S
190,191,1,2,"Pinsky, Mrs. (Rosa)",female,32.00,0,0,234604,13.0000,NaN,S
192,193,1,3,"Andersen-Jensen, Miss. Carla Christine Nielsine",female,19.00,1,0,350046,7.8542,NaN,S
193,194,1,2,"Navratil, Master. Michel M",male,3.00,1,1,230080,26.0000,F2,S
194,195,1,1,"Brown, Mrs. James Joseph (Margaret Tobin)",female,44.00,0,0,PC 17610,27.7208,B4,C
195,196,1,1,"Lurette, Miss. Elise",female,58.00,0,0,PC 17569,146.5208,B80,C
198,199,1,3,"Madigan, Miss. Margaret ""Maggie""",female,NaN,0,0,370370,7.7500,NaN,Q
204,205,1,3,"Cohen, Mr. Gurshon ""Gus""",male,18.00,0,0,A/5 3540,8.0500,NaN,S
207,208,1,3,"Albimona, Mr. Nassef Cassem",male,26.00,0,0,2699,18.7875,NaN,C
208,209,1,3,"Carr, Miss. Helen ""Ellen""",female,16.00,0,0,367231,7.7500,NaN,Q
209,210,1,1,"Blank, Mr. Henry",male,40.00,0,0,112277,31.0000,A31,C
211,212,1,2,"Cameron, Miss. Clear Annie",female,35.00,0,0,F.C.C. 13528,21.0000,NaN,S
215,216,1,1,"Newell, Miss. Madeleine",female,31.00,1,0,35273,113.2750,D36,C
216,217,1,3,"Honkanen, Miss. Eliina",female,27.00,0,0,STON/O2. 3101283,7.9250,NaN,S
218,219,1,1,"Bazzani, Miss. Albina",female,32.00,0,0,11813,76.2917,D15,C
220,221,1,3,"Sunderland, Mr. Victor Francis",male,16.00,0,0,SOTON/OQ 392089,8.0500,NaN,S
224,225,1,1,"Hoyt, Mr. Frederick Maxfield",male,38.00,1,0,19943,90.0000,C93,S
226,227,1,2,"Mellors, Mr. William John",male,19.00,0,0,SW/PP 751,10.5000,NaN,S
230,231,1,1,"Harris, Mrs. Henry Birkhardt (Irene Wallach)",female,35.00,1,0,36973,83.4750,C83,S
233,234,1,3,"Asplund, Miss. Lillian Gertrud",female,5.00,4,2,347077,31.3875,NaN,S
237,238,1,2,"Collyer, Miss. Marjorie ""Lottie""",female,8.00,0,2,C.A. 31921,26.2500,NaN,S
241,242,1,3,"Murphy, Miss. Katherine ""Kate""",female,NaN,1,0,367230,15.5000,NaN,Q
247,248,1,2,"Hamalainen, Mrs. William (Anna)",female,24.00,0,2,250649,14.5000,NaN,S
248,249,1,1,"Beckwith, Mr. Richard Leonard",male,37.00,1,1,11751,52.5542,D35,S
255,256,1,3,"Touma, Mrs. Darwis (Hanne Youssef Razi)",female,29.00,0,2,2650,15.2458,NaN,C
256,257,1,1,"Thorne, Mrs. Gertrude Maybelle",female,NaN,0,0,PC 17585,79.2000,NaN,C
257,258,1,1,"Cherry, Miss. Gladys",female,30.00,0,0,110152,86.5000,B77,S
258,259,1,1,"Ward, Miss. Anna",female,35.00,0,0,PC 17755,512.3292,NaN,C
259,260,1,2,"Parrish, Mrs. (Lutie Davis)",female,50.00,0,1,230433,26.0000,NaN,S
261,262,1,3,"Asplund, Master. Edvin Rojj Felix",male,3.00,4,2,347077,31.3875,NaN,S
267,268,1,3,"Persson, Mr. Ernst Ulrik",male,25.00,1,0,347083,7.7750,NaN,S
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.00,0,1,PC 17582,153.4625,C125,S
269,270,1,1,"Bissette, Miss. Amelia",female,35.00,0,0,PC 17760,135.6333,C99,S
271,272,1,3,"Tornquist, Mr. William Henry",male,25.00,0,0,LINE,0.0000,NaN,S
272,273,1,2,"Mellinger, Mrs. (Elizabeth Anne Maidment)",female,41.00,0,1,250644,19.5000,NaN,S
274,275,1,3,"Healy, Miss. Hanora ""Nora""",female,NaN,0,0,370375,7.7500,NaN,Q
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.00,1,0,13502,77.9583,D7,S
279,280,1,3,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35.00,1,1,C.A. 2673,20.2500,NaN,S
283,284,1,3,"Dorking, Mr. Edward Arthur",male,19.00,0,0,A/5. 10482,8.0500,NaN,S
286,287,1,3,"de Mulder, Mr. Theodore",male,30.00,0,0,345774,9.5000,NaN,S
288,289,1,2,"Hosono, Mr. Masabumi",male,42.00,0,0,237798,13.0000,NaN,S
289,290,1,3,"Connolly, Miss. Kate",female,22.00,0,0,370373,7.7500,NaN,Q
290,291,1,1,"Barber, Miss. Ellen ""Nellie""",female,26.00,0,0,19877,78.8500,NaN,S
291,292,1,1,"Bishop, Mrs. Dickinson H (Helen Walton)",female,19.00,1,0,11967,91.0792,B49,C
298,299,1,1,"Saalfeld, Mr. Adolphe",male,NaN,0,0,19988,30.5000,C106,S
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.00,0,1,PC 17558,247.5208,B58 B60,C
300,301,1,3,"Kelly, Miss. Anna Katherine ""Annie Kate""",female,NaN,0,0,9234,7.7500,NaN,Q
301,302,1,3,"McCoy, Mr. Bernard",male,NaN,2,0,367226,23.2500,NaN,Q
303,304,1,2,"Keane, Miss. Nora A",female,NaN,0,0,226593,12.3500,E101,Q
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
306,307,1,1,"Fleming, Miss. Margaret",female,NaN,0,0,17421,110.8833,NaN,C
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C
309,310,1,1,"Francatelli, Miss. Laura Mabel",female,30.00,0,0,PC 17485,56.9292,E36,C
310,311,1,1,"Hays, Miss. Margaret Bechstein",female,24.00,0,0,11767,83.1583,C54,C
311,312,1,1,"Ryerson, Miss. Emily Borie",female,18.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
315,316,1,3,"Nilsson, Miss. Helmina Josefina",female,26.00,0,0,347470,7.8542,NaN,S
316,317,1,2,"Kantor, Mrs. Sinai (Miriam Sternin)",female,24.00,1,0,244367,26.0000,NaN,S
318,319,1,1,"Wick, Miss. Mary Natalie",female,31.00,0,2,36928,164.8667,C7,S
319,320,1,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",female,40.00,1,1,16966,134.5000,E34,C
322,323,1,2,"Slayter, Miss. Hilda Mary",female,30.00,0,0,234818,12.3500,NaN,Q
323,324,1,2,"Caldwell, Mrs. Albert Francis (Sylvia Mae Harb...",female,22.00,1,1,248738,29.0000,NaN,S
325,326,1,1,"Young, Miss. Marie Grice",female,36.00,0,0,PC 17760,135.6333,C32,C
327,328,1,2,"Ball, Mrs. (Ada E Hall)",female,36.00,0,0,28551,13.0000,D,S
328,329,1,3,"Goldsmith, Mrs. Frank John (Emily Alice Brown)",female,31.00,1,1,363291,20.5250,NaN,S
329,330,1,1,"Hippach, Miss. Jean Gertrude",female,16.00,0,1,111361,57.9792,B18,C
330,331,1,3,"McCoy, Miss. Agnes",female,NaN,2,0,367226,23.2500,NaN,Q
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,1,0,PC 17611,133.6500,NaN,S
337,338,1,1,"Burns, Miss. Elizabeth Margaret",female,41.00,0,0,16966,134.5000,E40,C
338,339,1,3,"Dahl, Mr. Karl Edwart",male,45.00,0,0,7598,8.0500,NaN,S
340,341,1,2,"Navratil, Master. Edmond Roger",male,2.00,1,1,230080,26.0000,F2,S
341,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.00,3,2,19950,263.0000,C23 C25 C27,S
345,346,1,2,"Brown, Miss. Amelia ""Mildred""",female,24.00,0,0,248733,13.0000,F33,S
346,347,1,2,"Smith, Miss. Marion Elsie",female,40.00,0,0,31418,13.0000,NaN,S
347,348,1,3,"Davison, Mrs. Thomas Henry (Mary E Finck)",female,NaN,1,0,386525,16.1000,NaN,S
348,349,1,3,"Coutts, Master. William Loch ""William""",male,3.00,1,1,C.A. 37671,15.9000,NaN,S
356,357,1,1,"Bowerman, Miss. Elsie Edith",female,22.00,0,1,113505,55.0000,E33,S
358,359,1,3,"McGovern, Miss. Mary",female,NaN,0,0,330931,7.8792,NaN,Q
359,360,1,3,"Mockler, Miss. Helen Mary ""Ellie""",female,NaN,0,0,330980,7.8792,NaN,Q
366,367,1,1,"Warren, Mrs. Frank Manley (Anna Sophia Atkinson)",female,60.00,1,0,110813,75.2500,D37,C
367,368,1,3,"Moussa, Mrs. (Mantoura Boulos)",female,NaN,0,0,2626,7.2292,NaN,C
368,369,1,3,"Jermyn, Miss. Annie",female,NaN,0,0,14313,7.7500,NaN,Q
369,370,1,1,"Aubart, Mme. Leontine Pauline",female,24.00,0,0,PC 17477,69.3000,B35,C
370,371,1,1,"Harder, Mr. George Achilles",male,25.00,1,0,11765,55.4417,E50,C
375,376,1,1,"Meyer, Mrs. Edgar Joseph (Leila Saks)",female,NaN,1,0,PC 17604,82.1708,NaN,C
376,377,1,3,"Landergren, Miss. Aurora Adelia",female,22.00,0,0,C 7077,7.2500,NaN,S
380,381,1,1,"Bidois, Miss. Rosalie",female,42.00,0,0,PC 17757,227.5250,NaN,C
381,382,1,3,"Nakid, Miss. Maria (""Mary"")",female,1.00,0,2,2653,15.7417,NaN,C
383,384,1,1,"Holverson, Mrs. Alexander Oskar (Mary Aline To...",female,35.00,1,0,113789,52.0000,NaN,S
387,388,1,2,"Buss, Miss. Kate",female,36.00,0,0,27849,13.0000,NaN,S
389,390,1,2,"Lehmann, Miss. Bertha",female,17.00,0,0,SC 1748,12.0000,NaN,C
390,391,1,1,"Carter, Mr. William Ernest",male,36.00,1,2,113760,120.0000,B96 B98,S
391,392,1,3,"Jansson, Mr. Carl Olof",male,21.00,0,0,350034,7.7958,NaN,S
393,394,1,1,"Newell, Miss. Marjorie",female,23.00,1,0,35273,113.2750,D36,C
394,395,1,3,"Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengt...",female,24.00,0,2,PP 9549,16.7000,G6,S
399,400,1,2,"Trout, Mrs. William H (Jessie L)",female,28.00,0,0,240929,12.6500,NaN,S
400,401,1,3,"Niskanen, Mr. Juha",male,39.00,0,0,STON/O 2. 3101289,7.9250,NaN,S
407,408,1,2,"Richards, Master. William Rowe",male,3.00,1,1,29106,18.7500,NaN,S
412,413,1,1,"Minahan, Miss. Daisy E",female,33.00,1,0,19928,90.0000,C78,Q
414,415,1,3,"Sundman, Mr. Johan Julian",male,44.00,0,0,STON/O 2. 3101269,7.9250,NaN,S
416,417,1,2,"Drew, Mrs. James Vivian (Lulu Thorne Christian)",female,34.00,1,1,28220,32.5000,NaN,S
417,418,1,2,"Silven, Miss. Lyyli Karoliina",female,18.00,0,2,250652,13.0000,NaN,S
426,427,1,2,"Clarke, Mrs. Charles V (Ada Maria Winfield)",female,28.00,1,0,2003,26.0000,NaN,S
427,428,1,2,"Phillips, Miss. Kate Florence (""Mrs Kate Louis...",female,19.00,0,0,250655,26.0000,NaN,S
429,430,1,3,"Pickard, Mr. Berk (Berk Trembisky)",male,32.00,0,0,SOTON/O.Q. 392078,8.0500,E10,S
430,431,1,1,"Bjornstrom-Steffansson, Mr. Mauritz Hakan",male,28.00,0,0,110564,26.5500,C52,S
431,432,1,3,"Thorneycroft, Mrs. Percival (Florence Kate White)",female,NaN,1,0,376564,16.1000,NaN,S
432,433,1,2,"Louch, Mrs. Charles Alexander (Alice Adelaide ...",female,42.00,1,0,SC/AH 3085,26.0000,NaN,S
435,436,1,1,"Carter, Miss. Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
437,438,1,2,"Richards, Mrs. Sidney (Emily Hocking)",female,24.00,2,3,29106,18.7500,NaN,S
440,441,1,2,"Hart, Mrs. Benjamin (Esther Ada Bloomfield)",female,45.00,1,1,F.C.C. 13529,26.2500,NaN,S
443,444,1,2,"Reynaldo, Ms. Encarnacion",female,28.00,0,0,230434,13.0000,NaN,S
444,445,1,3,"Johannesen-Bratthammer, Mr. Bernt",male,NaN,0,0,65306,8.1125,NaN,S
445,446,1,1,"Dodge, Master. Washington",male,4.00,0,2,33638,81.8583,A34,S
446,447,1,2,"Mellinger, Miss. Madeleine Violet",female,13.00,0,1,250644,19.5000,NaN,S
447,448,1,1,"Seward, Mr. Frederic Kimber",male,34.00,0,0,113794,26.5500,NaN,S
448,449,1,3,"Baclini, Miss. Marie Catherine",female,5.00,2,1,2666,19.2583,NaN,C
449,450,1,1,"Peuchen, Major. Arthur Godfrey",male,52.00,0,0,113786,30.5000,C104,S
453,454,1,1,"Goldenberg, Mr. Samuel L",male,49.00,1,0,17453,89.1042,C92,C
455,456,1,3,"Jalsevac, Mr. Ivan",male,29.00,0,0,349240,7.8958,NaN,C
457,458,1,1,"Kenyon, Mrs. Frederick R (Marion)",female,NaN,1,0,17464,51.8625,D21,S
458,459,1,2,"Toomey, Miss. Ellen",female,50.00,0,0,F.C.C. 13531,10.5000,NaN,S
460,461,1,1,"Anderson, Mr. Harry",male,48.00,0,0,19952,26.5500,E12,S
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
472,473,1,2,"West, Mrs. Edwy Arthur (Ada Mary Worth)",female,33.00,1,2,C.A. 34651,27.7500,NaN,S
473,474,1,2,"Jerwan, Mrs. Amin S (Marie Marthe Thuillard)",female,23.00,0,0,SC/AH Basle 541,13.7917,D,C
479,480,1,3,"Hirvonen, Miss. Hildur E",female,2.00,0,1,3101298,12.2875,NaN,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.00,0,0,4134,9.5875,NaN,S
484,485,1,1,"Bishop, Mr. Dickinson H",male,25.00,1,0,11967,91.0792,B49,C
486,487,1,1,"Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)",female,35.00,1,0,19943,90.0000,C93,S
489,490,1,3,"Coutts, Master. Eden Leslie ""Neville""",male,9.00,1,1,C.A. 37671,15.9000,NaN,S
496,497,1,1,"Eustis, Miss. Elizabeth Mussey",female,54.00,1,0,36947,78.2667,D20,C
504,505,1,1,"Maioni, Miss. Roberta",female,16.00,0,0,110152,86.5000,B79,S
506,507,1,2,"Quick, Mrs. Frederick Charles (Jane Richards)",female,33.00,0,2,26360,26.0000,NaN,S
507,508,1,1,"Bradley, Mr. George (""George Arthur Brayton"")",male,NaN,0,0,111427,26.5500,NaN,S
509,510,1,3,"Lang, Mr. Fang",male,26.00,0,0,1601,56.4958,NaN,S
510,511,1,3,"Daly, Mr. Eugene Patrick",male,29.00,0,0,382651,7.7500,NaN,Q
512,513,1,1,"McGough, Mr. James Robert",male,36.00,0,0,PC 17473,26.2875,E25,S
513,514,1,1,"Rothschild, Mrs. Martin (Elizabeth L. Barrett)",female,54.00,1,0,PC 17603,59.4000,NaN,C
516,517,1,2,"Lemore, Mrs. (Amelia Milley)",female,34.00,0,0,C.A. 34260,10.5000,F33,S
518,519,1,2,"Angle, Mrs. William A (Florence ""Mary"" Agnes H...",female,36.00,1,0,226875,26.0000,NaN,S
520,521,1,1,"Perreault, Miss. Anne",female,30.00,0,0,12749,93.5000,B73,S
523,524,1,1,"Hippach, Mrs. Louis Albert (Ida Sophia Fischer)",female,44.00,0,1,111361,57.9792,B18,C
526,527,1,2,"Ridsdale, Miss. Lucy",female,50.00,0,0,W./C. 14258,10.5000,NaN,S
530,531,1,2,"Quick, Miss. Phyllis May",female,2.00,1,1,26360,26.0000,NaN,S
533,534,1,3,"Peter, Mrs. Catherine (Catherine Rizk)",female,NaN,0,2,2668,22.3583,NaN,C
535,536,1,2,"Hart, Miss. Eva Miriam",female,7.00,0,2,F.C.C. 13529,26.2500,NaN,S
537,538,1,1,"LeRoy, Miss. Bertha",female,30.00,0,0,PC 17761,106.4250,NaN,C
539,540,1,1,"Frolicher, Miss. Hedwig Margaritha",female,22.00,0,2,13568,49.5000,B39,C
540,541,1,1,"Crosby, Miss. Harriet R",female,36.00,0,2,WE/P 5735,71.0000,B22,S
543,544,1,2,"Beane, Mr. Edward",male,32.00,1,0,2908,26.0000,NaN,S
546,547,1,2,"Beane, Mrs. Edward (Ethel Clarke)",female,19.00,1,0,2908,26.0000,NaN,S
547,548,1,2,"Padro y Manent, Mr. Julian",male,NaN,0,0,SC/PARIS 2146,13.8625,NaN,C
549,550,1,2,"Davies, Master. John Morgan Jr",male,8.00,1,1,C.A. 33112,36.7500,NaN,S
550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C
553,554,1,3,"Leeni, Mr. Fahim (""Philip Zenni"")",male,22.00,0,0,2620,7.2250,NaN,C
554,555,1,3,"Ohman, Miss. Velin",female,22.00,0,0,347085,7.7750,NaN,S
556,557,1,1,"Duff Gordon, Lady. (Lucille Christiana Sutherl...",female,48.00,1,0,11755,39.6000,A16,C
558,559,1,1,"Taussig, Mrs. Emil (Tillie Mandelbaum)",female,39.00,1,1,110413,79.6500,E67,S
559,560,1,3,"de Messemaeker, Mrs. Guillaume Joseph (Emma)",female,36.00,1,0,345572,17.4000,NaN,S
569,570,1,3,"Jonsson, Mr. Carl",male,32.00,0,0,350417,7.8542,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.00,0,0,S.W./PP 752,10.5000,NaN,S
571,572,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.00,2,0,11769,51.4792,C101,S
572,573,1,1,"Flynn, Mr. John Irwin (""Irving"")",male,36.00,0,0,PC 17474,26.3875,E25,S
573,574,1,3,"Kelly, Miss. Mary",female,NaN,0,0,14312,7.7500,NaN,Q
576,577,1,2,"Garside, Miss. Ethel",female,34.00,0,0,243880,13.0000,NaN,S
577,578,1,1,"Silvey, Mrs. William Baird (Alice Munger)",female,39.00,1,0,13507,55.9000,E44,S
579,580,1,3,"Jussila, Mr. Eiriik",male,32.00,0,0,STON/O 2. 3101286,7.9250,NaN,S
580,581,1,2,"Christy, Miss. Julie Rachel",female,25.00,1,1,237789,30.0000,NaN,S
581,582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.00,1,1,17421,110.8833,C68,C
585,586,1,1,"Taussig, Miss. Ruth",female,18.00,0,2,110413,79.6500,E68,S
587,588,1,1,"Frolicher-Stehli, Mr. Maxmillian",male,60.00,1,1,13567,79.2000,B41,C
591,592,1,1,"Stephenson, Mrs. Walter Bertram (Martha Eustis)",female,52.00,1,0,36947,78.2667,D20,C
596,597,1,2,"Leitch, Miss. Jessie Wills",female,NaN,0,0,248727,33.0000,NaN,S
599,600,1,1,"Duff Gordon, Sir. Cosmo Edmund (""Mr Morgan"")",male,49.00,1,0,PC 17485,56.9292,A20,C
600,601,1,2,"Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...",female,24.00,2,1,243847,27.0000,NaN,S
604,605,1,1,"Homer, Mr. Harry (""Mr E Haven"")",male,35.00,0,0,111426,26.5500,NaN,C
607,608,1,1,"Daniel, Mr. Robert Williams",male,27.00,0,0,113804,30.5000,NaN,S

In [24]:
survival = titanic_train[titanic_train["Survived"] == 1]
print(len(survival))
survival['Sex'].value_counts()

342

female    233
male      109
Name: Sex, dtype: int64

In [119]:
titanic_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'test'],
      dtype='object')

In [120]:
titanic_train.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,test
count,156.000000,156.000000,156.000000,126.000000,156.000000,156.000000,156.000000,156.0
mean,78.500000,0.346154,2.423077,28.141508,0.615385,0.397436,28.109587,0.0
std,45.177428,0.477275,0.795459,14.613880,1.056235,0.870146,39.401047,0.0
min,1.000000,0.000000,1.000000,0.830000,0.000000,0.000000,6.750000,0.0
25%,39.750000,0.000000,2.000000,19.000000,0.000000,0.000000,8.003150,0.0
50%,78.500000,0.000000,3.000000,26.000000,0.000000,0.000000,14.454200,0.0
75%,117.250000,1.000000,3.000000,35.000000,1.000000,0.000000,30.371850,0.0
max,156.000000,1.000000,3.000000,71.000000,5.000000,5.000000,263.000000,0.0

In [179]:
new_Pclass = pd.Categorical(titanic_train["Pclass"])
new_Pclass

[3, 1, 3, 1, 3, ..., 1, 3, 3, 3, 1]
Length: 156
Categories (3, int64): [1, 2, 3]

In [193]:
new_Pclass = pd.Categorical(titanic_train["Pclass"])

new_Pclass

[90, dfsf, 90, dfsf, 90, ..., dfsf, 90, 90, 90, dfsf]
Length: 156
Categories (3, object): [dfsf, 9, 90]

In [181]:
titanic_train["Cabin"].unique()   # Check unique cabins

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2'], dtype=object)

In [7]:
# to create a new column to 1st leter of cabin 
import numpy as np 
char_cabin = titanic_train["Cabin"].astype(str) # Convert data to str

# for i in char_cabin:
#   new_cabin.append(i[0])

new_Cabin = [cabin[0] for cabin in char_cabin] # Take first letter in list

new_Cabin = pd.Categorical(new_Cabin)
#new_Cabin
new_Cabin

[n, C, n, C, n, ..., C, n, n, n, n]
Length: 156
Categories (8, object): [A, B, C, D, E, F, G, n]

In [8]:
titanic_train["Cabin1"] = new_Cabin
titanic_train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Cabin1
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,n
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,n
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,C
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,n

In [27]:
titanic_train["Age"].isnull()  #all index whereage is null

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888     True
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [8]:
titanic_train[titanic_train["Age"].isnull()==True]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
32,33,1,3,"Glynn, Miss. Mary Agatha",female,NaN,0,0,335677,7.7500,NaN,Q
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
42,43,0,3,"Kraeff, Mr. Theodor",male,NaN,0,0,349253,7.8958,NaN,C
45,46,0,3,"Rogers, Mr. William John",male,NaN,0,0,S.C./A.4. 23567,8.0500,NaN,S
46,47,0,3,"Lennon, Mr. Denis",male,NaN,1,0,370371,15.5000,NaN,Q
47,48,1,3,"O'Driscoll, Miss. Bridget",female,NaN,0,0,14311,7.7500,NaN,Q
48,49,0,3,"Samaan, Mr. Youssef",male,NaN,2,0,2662,21.6792,NaN,C
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
64,65,0,1,"Stewart, Mr. Albert A",male,NaN,0,0,PC 17605,27.7208,NaN,C
65,66,1,3,"Moubarek, Master. Gerios",male,NaN,1,1,2661,15.2458,NaN,C
76,77,0,3,"Staneff, Mr. Ivan",male,NaN,0,0,349208,7.8958,NaN,S
77,78,0,3,"Moutal, Mr. Rahamin Haim",male,NaN,0,0,374746,8.0500,NaN,S
82,83,1,3,"McDermott, Miss. Brigdet Delia",female,NaN,0,0,330932,7.7875,NaN,Q
87,88,0,3,"Slocovski, Mr. Selman Francis",male,NaN,0,0,SOTON/OQ 392086,8.0500,NaN,S
95,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,8.0500,NaN,S
101,102,0,3,"Petroff, Mr. Pastcho (""Pentcho"")",male,NaN,0,0,349215,7.8958,NaN,S
107,108,1,3,"Moss, Mr. Albert Johan",male,NaN,0,0,312991,7.7750,NaN,S
109,110,1,3,"Moran, Miss. Bertha",female,NaN,1,0,371110,24.1500,NaN,Q
121,122,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.0500,NaN,S
126,127,0,3,"McMahon, Mr. Martin",male,NaN,0,0,370372,7.7500,NaN,Q
128,129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
140,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S

In [28]:
missing = np.where(titanic_train["Age"].isnull() == True)
missing

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185, 186,
        196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260, 264,
        270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324, 330,
        334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384, 388,
        409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454, 457,
        459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502, 507,
        511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560, 563,
        564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611, 612,
        613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674, 680,
        692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766, 768,
        773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 832, 837,
        839, 846, 849, 859, 863, 868, 878, 888], dtype=int64),)

In [29]:
max(titanic_train["Fare"])

512.3292

In [20]:
titanic_train["Fare"]==max(titanic_train["Fare"])

0      False
1      False
2      False
3      False
4      False
       ...
151    False
152    False
153    False
154    False
155    False
Name: Fare, Length: 156, dtype: bool

In [30]:
np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))

(array([258, 679, 737], dtype=int64),)

In [31]:
titanic_train.iloc[np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C

In [30]:
np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))

(array([27, 88]),)

In [31]:
len(missing[0])

30

In [194]:
titanic_train["Family"] = titanic_train["SibSp"] + titanic_train["Parch"]
titanic_train["Family"]
most_family = np.where(titanic_train["Family"] == max(titanic_train["Family"]))
most_family

(array([59, 71]),)

In [135]:
titanic_train["Family"] = titanic_train["SibSp"] + titanic_train["Parch"]

most_family = np.where(titanic_train["Family"] == max(titanic_train["Family"]))
most_family
titanic_train.iloc[most_family]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,test,Cabin1,Family
59,60,0,3,"Goodwin, Master. William Frederick",male,11.0,5,2,CA 2144,46.9,NaN,S,0,n,7
71,72,0,3,"Goodwin, Miss. Lillian Amy",female,16.0,5,2,CA 2144,46.9,NaN,S,0,n,7

In [196]:
import numpy as np
import pandas as pd

labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

print ("Labels:", labels)
print("My data:", my_data)
print("Dictionary:", d)
pd.Series(my_data, index=labels)

Labels: ['a', 'b', 'c']
My data: [10, 20, 30]
Dictionary: {'a': 10, 'b': 20, 'c': 30}

a    10
b    20
c    30
dtype: int64

In [35]:
pd.Series(my_data, index=labels)

a    10
b    20
c    30
dtype: int64

In [199]:
print ("\nHolding numerical data\n",'-'*25, sep='')
print(pd.Series(arr)[1])

Holding numerical data
-------------------------
20

In [198]:
print ("\nHolding text labels\n",'-'*20, sep='')
print(pd.Series(labels))

Holding text labels
--------------------
0    a
1    b
2    c
dtype: object

In [201]:

d = {'a':"kjhk",'b':20,'c':30}
d.items
pd.DataFrame(d,index = ['a','b','c'])

      a   b   c
a  kjhk  20  30
b  kjhk  20  30
c  kjhk  20  30

In [203]:
print ("\nHolding objects from a dictionary\n",'-'*40, sep='')
print(pd.Series([type, sum, max]))

Holding objects from a dictionary
----------------------------------------
0             <class 'type'>
1    <built-in function sum>
2    <built-in function max>
dtype: object

In [216]:
ser1 = pd.Series([1,2,3,4],index = [2,4,6,8])
ser2 = pd.Series([1,2,5,4],['CA', 'OR', 'NV', 'AZ'])
ser1

2    1
4    2
6    3
8    4
dtype: int64

In [217]:
ser1[0:3:2]

2    1
6    3
dtype: int64

In [42]:
print ("\nIndexing by number (positional value in the series)\n",'-'*52, sep='')
print("Value for CA in ser1:", ser1[0])
print("Value for AZ in ser1:", ser1[3])
print("Value for NV in ser2:", ser2[2])
ser1

Indexing by number (positional value in the series)
----------------------------------------------------
Value for CA in ser1: 1
Value for AZ in ser1: 4
Value for NV in ser2: 5

CA    1
OR    2
CO    3
AZ    4
dtype: int64

In [215]:
print ("\nIndexing by a range\n",'-'*25, sep='')
print ("Value for OR, CO, and AZ in ser1:\n", ser1[0:3:2], sep='')

Indexing by a range
-------------------------
Value for OR, CO, and AZ in ser1:
100    1
CO     3
dtype: int64

In [3]:
ser1 = pd.Series([1,2,3,4],['CA', 'OR', 'CO', 'CA'])
ser2 = pd.Series([1,2,5,4],['CA', 'NV', 'AZ','OR'])
ser3 = ser1+ser2
ser3

AZ    NaN
CA    2.0
CA    5.0
CO    NaN
NV    NaN
OR    6.0
dtype: float64

In [45]:
print ("\nAfter adding the two series, the result looks like this...\n",'-'*59, sep='')
print(ser3)
print("\nPython tries to add values where it finds common index name, and puts NaN where indices are missing\n")

After adding the two series, the result looks like this...
-----------------------------------------------------------
AZ    NaN
CA    2.0
CA    5.0
CO    NaN
NV    NaN
OR    6.0
dtype: float64

Python tries to add values where it finds common index name, and puts NaN where indices are missing

In [46]:
print ("\nThe idea works even for multiplication...\n",'-'*43, sep='')
print (ser1*ser2)

The idea works even for multiplication...
-------------------------------------------
AZ    NaN
CA    1.0
CA    4.0
CO    NaN
NV    NaN
OR    8.0
dtype: float64

In [4]:
from numpy.random import randn as rn
#np.random.seed(101)
matrix_data = rn(5,4)
row_labels = ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']

df = pd.DataFrame(matrix_data,row_labels,column_headings)
#print("\nThe data frame looks like\n",'-'*45, sep='')
df

          W         X         Y         Z
A -0.964125  1.620393  0.862816  0.877327
B -1.027721 -0.235968  0.395199  0.105760
C  0.638297  0.191965 -0.910558 -0.262456
D  0.361685 -0.391555 -0.986207  0.231495
E -0.090619 -1.711412  0.552947 -1.348353

In [5]:
df.iloc[2]  #index position

W    0.638297
X    0.191965
Y   -0.910558
Z   -0.262456
Name: C, dtype: float64

In [8]:
df.loc['A']   # label of row

W   -0.964125
X    1.620393
Y    0.862816
Z    0.877327
Name: A, dtype: float64

In [6]:
print("\nType of the pair of columns: ", type(df[['X','Z']]), sep='')
print ("\nSo, for more than one column, the object turns into a DataFrame")

Type of the pair of columns: <class 'pandas.core.frame.DataFrame'>

So, for more than one column, the object turns into a DataFrame

In [7]:
print("\nThe 'X' column accessed by DOT method (NOT recommended)\n",'-'*55, sep='')
print(df["X"])

The 'X' column accessed by DOT method (NOT recommended)
-------------------------------------------------------
A    1.620393
B   -0.235968
C    0.191965
D   -0.391555
E   -1.711412
Name: X, dtype: float64

In [9]:
print("\nA column is created by assigning it in relation to an existing column\n",'-'*75, sep='')
df['New'] = df['X']+df['Z']
df['New (Sum of X and Z)'] = df['X']+df['Z']
print(df)

A column is created by assigning it in relation to an existing column
---------------------------------------------------------------------------
          W         X         Y         Z       New  New (Sum of X and Z)
A -0.964125  1.620393  0.862816  0.877327  2.497720              2.497720
B -1.027721 -0.235968  0.395199  0.105760 -0.130209             -0.130209
C  0.638297  0.191965 -0.910558 -0.262456 -0.070492             -0.070492
D  0.361685 -0.391555 -0.986207  0.231495 -0.160059             -0.160059
E -0.090619 -1.711412  0.552947 -1.348353 -3.059765             -3.059765

In [11]:
df.iloc[2,1]

0.19196476782656316

In [14]:
df.iloc[1:4 , 2:4]

          Y         Z
B  0.395199  0.105760
C -0.910558 -0.262456
D -0.986207  0.231495

In [52]:
df

          W         X         Y         Z       New  New (Sum of X and Z)
A  0.150705 -0.446910  1.669238 -1.138071 -1.584981             -1.584981
B  0.462929  0.129871  0.128628  1.865870  1.995741              1.995741
C  0.783021  0.561695 -1.608215 -0.997146 -0.435451             -0.435451
D  1.124639  0.626070 -0.129314 -0.075665  0.550405              0.550405
E  0.133687  1.988570  0.416920 -0.729497  1.259073              1.259073

In [17]:
print("\nA column is dropped by using df.drop() method\n",'-'*55, sep=' ')
df.drop("C",inplace=True) # Notice the axis=1 option, axis = 0 is default, so one has to change it to 1

A column is dropped by using df.drop() method
 -------------------------------------------------------

In [20]:
df

          W         X         Y         Z       New  New (Sum of X and Z)
A -0.964125  1.620393  0.862816  0.877327  2.497720              2.497720
B -1.027721 -0.235968  0.395199  0.105760 -0.130209             -0.130209
D  0.361685 -0.391555 -0.986207  0.231495 -0.160059             -0.160059
E -0.090619 -1.711412  0.552947 -1.348353 -3.059765             -3.059765

In [22]:
df1=df.drop('X',axis =1)   #1 =coloum , 0 = row
#print("\nA row (index) is dropped by using df.drop() method and axis=0\n",'-'*65, sep='')
print(df1)

A row (index) is dropped by using df.drop() method and axis=0
-----------------------------------------------------------------
          W         Y         Z       New  New (Sum of X and Z)
A -0.964125  0.862816  0.877327  2.497720              2.497720
B -1.027721  0.395199  0.105760 -0.130209             -0.130209
D  0.361685 -0.986207  0.231495 -0.160059             -0.160059
E -0.090619  0.552947 -1.348353 -3.059765             -3.059765

In [56]:
print("\nAn in-place change can be done by making inplace=True in the drop method\n",'-'*75, sep='')
df.drop('New (Sum of X and Z)', axis=1, inplace=True)
print(df)

An in-place change can be done by making inplace=True in the drop method
---------------------------------------------------------------------------
          W         X         Y         Z       New
A  0.150705 -0.446910  1.669238 -1.138071 -1.584981
B  0.462929  0.129871  0.128628  1.865870  1.995741
D  1.124639  0.626070 -0.129314 -0.075665  0.550405
E  0.133687  1.988570  0.416920 -0.729497  1.259073

In [11]:
### Selecting/indexing Rows
#* Label-based 'loc' method
#* Index (numeric) 'iloc' method
df

          W         X         Y         Z
A  0.463014  2.351775  0.355781  0.127966
B  0.783331  1.794840 -0.892002 -0.596769
C  0.119252 -0.020044 -2.072349  2.130845
D  0.128286  0.206469 -1.227162  1.602765
E -0.197037  1.957458  0.238325  1.542864

In [58]:
print("\nLabel-based 'loc' method can be used for selecting row(s)\n",'-'*60, sep='')
print("\nSingle row\n")
print(df.iloc[3])

Label-based 'loc' method can be used for selecting row(s)
------------------------------------------------------------

Single row

W      0.133687
X      1.988570
Y      0.416920
Z     -0.729497
New    1.259073
Name: E, dtype: float64

In [59]:
print("\nMultiple rows\n")
print(df.loc[['B','C']])          #index first and last row

Multiple rows

          W         X         Y        Z       New
B  0.462929  0.129871  0.128628  1.86587  1.995741
C       NaN       NaN       NaN      NaN       NaN

/Users/sudhanshukumar/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike

In [60]:
print("\nIndex position based 'iloc' method can be used for selecting row(s)\n",'-'*70, sep='')
print("\nSingle row\n")
print(df.iloc[2])

Index position based 'iloc' method can be used for selecting row(s)
----------------------------------------------------------------------

Single row

W      1.124639
X      0.626070
Y     -0.129314
Z     -0.075665
New    0.550405
Name: D, dtype: float64

In [61]:
print("\nMultiple rows\n")
print(df.iloc[[1,2]])

Multiple rows

          W         X         Y         Z       New
B  0.462929  0.129871  0.128628  1.865870  1.995741
D  1.124639  0.626070 -0.129314 -0.075665  0.550405

In [62]:
#### Subsetting DataFrame

In [63]:

matrix_data = rn(5,4)
row_labels = ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']
df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)

In [64]:
print("\nThe DatFrame\n",'-'*45, sep='')
print(df)

The DatFrame
---------------------------------------------
          W         X         Y         Z
A -0.320697  1.586737 -0.962361  0.984044
B -0.236481 -0.520044 -0.137304 -1.719868
C -0.415743 -0.280577  1.293790 -0.495861
D -0.564725 -1.331318 -1.098884  0.385147
E  1.079266  1.101438  1.097766  0.452282

In [65]:
print("\nElement at row 'B' and column 'Y' is\n") 
print(df.loc[['B','C'],['Y','W']])

Element at row 'B' and column 'Y' is

          Y         W
B -0.137304 -0.236481
C  1.293790 -0.415743

In [66]:
print("\nSubset comprising of rows B and D, and columns W and Y, is\n")
df.iloc[[1,2,3],[0,1]]

Subset comprising of rows B and D, and columns W and Y, is

          W         X
B -0.236481 -0.520044
C -0.415743 -0.280577
D -0.564725 -1.331318

In [67]:
print(df.loc[['B','C'],])

          W         X         Y         Z
B -0.236481 -0.520044 -0.137304 -1.719868
C -0.415743 -0.280577  1.293790 -0.495861

In [68]:
print("\nThe DataFrame\n",'-'*45, sep='')
print(df)

The DataFrame
---------------------------------------------
          W         X         Y         Z
A -0.320697  1.586737 -0.962361  0.984044
B -0.236481 -0.520044 -0.137304 -1.719868
C -0.415743 -0.280577  1.293790 -0.495861
D -0.564725 -1.331318 -1.098884  0.385147
E  1.079266  1.101438  1.097766  0.452282

In [23]:
print("\nBoolean DataFrame(s) where we are checking if the values are greater than 0\n",'-'*75, sep='')
print(df>0)

Boolean DataFrame(s) where we are checking if the values are greater than 0
---------------------------------------------------------------------------
       W      X      Y      Z    New  New (Sum of X and Z)
A  False   True   True   True   True                  True
B  False  False   True   True  False                 False
D   True  False  False   True  False                 False
E  False  False   True  False  False                 False

In [70]:
print("\n")
print(df.loc[['A','B','C']]>0)

       W      X      Y      Z
A  False   True  False   True
B  False  False  False  False
C  False  False   True  False

In [71]:
booldf = df>0
print("\nDataFrame indexed by boolean dataframe\n",'-'*45, sep='')
print()df[booldf]

DataFrame indexed by boolean dataframe
---------------------------------------------
          W         X         Y         Z
A       NaN  1.586737       NaN  0.984044
B       NaN       NaN       NaN       NaN
C       NaN       NaN  1.293790       NaN
D       NaN       NaN       NaN  0.385147
E  1.079266  1.101438  1.097766  0.452282

In [72]:

import pandas as pd 
import numpy as np
matrix_data = np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')
row_labels = ['A','B','C','D','E']
column_headings = ['Age', 'Height', 'Weight']
matrix_data

matrix([[ 22,  66, 140],
        [ 42,  70, 148],
        [ 30,  62, 125],
        [ 35,  68, 160],
        [ 25,  62, 152]])

In [73]:
df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)
print("\nA new DataFrame\n",'-'*25, sep='')
print(df)

A new DataFrame
-------------------------
   Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152

In [74]:
df[df['Height']>65]

   Age  Height  Weight
A   22      66     140
B   42      70     148
D   35      68     160

In [75]:
print("\nRows with Height > 65 inch\n",'-'*35, sep='')
print(df[df['Height']>65])

Rows with Height > 65 inch
-----------------------------------
   Age  Height  Weight
A   22      66     140
B   42      70     148
D   35      68     160

In [76]:
df['Height']>65

A     True
B     True
C    False
D     True
E    False
Name: Height, dtype: bool

In [77]:
booldf1 = df['Height']>65
booldf2 = df['Weight']>145

In [78]:
print("\nRows with Height > 65 inch and Weight >145 lbs\n",'-'*55, sep='')
print(df[(booldf1) & (booldf2)])

Rows with Height > 65 inch and Weight >145 lbs
-------------------------------------------------------
   Age  Height  Weight
B   42      70     148
D   35      68     160

In [79]:
print("\nDataFrame with only Age and Weight columns whose Height > 65 inch\n",'-'*68, sep='')
print(df[booldf1][['Age','Weight']])

DataFrame with only Age and Weight columns whose Height > 65 inch
--------------------------------------------------------------------
   Age  Weight
A   22     140
B   42     148
D   35     160

In [80]:
matrix_data = np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')
row_labels = ['A','B','C','D','E']
column_headings = ['Age', 'Height', 'Weight']

In [81]:
df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)
print("\nThe DataFrame\n",'-'*25, sep='')
print(df)

The DataFrame
-------------------------
   Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152

In [82]:
print("\nAfter resetting index\n",'-'*35, sep='')
print(df.reset_index())

After resetting index
-----------------------------------
  index  Age  Height  Weight
0     A   22      66     140
1     B   42      70     148
2     C   30      62     125
3     D   35      68     160
4     E   25      62     152

In [83]:
print("\nAfter resetting index with 'drop' option TRUE\n",'-'*45, sep='')
print(df.reset_index(drop=True))
"Student Teacher Engineer Doctor Nurse".split()

After resetting index with 'drop' option TRUE
---------------------------------------------
   Age  Height  Weight
0   22      66     140
1   42      70     148
2   30      62     125
3   35      68     160
4   25      62     152

['Student', 'Teacher', 'Engineer', 'Doctor', 'Nurse']

In [84]:
print("\nAdding a new column 'Profession'\n",'-'*45, sep='')
df['Profession'] = "Student Teacher Engineer Doctor Nurse".split()
print(df)

Adding a new column 'Profession'
---------------------------------------------
   Age  Height  Weight Profession
A   22      66     140    Student
B   42      70     148    Teacher
C   30      62     125   Engineer
D   35      68     160     Doctor
E   25      62     152      Nurse

In [85]:
print("\nSetting 'Profession' column as index\n",'-'*45, sep='')
print (df.set_index('Profession'))

Setting 'Profession' column as index
---------------------------------------------
            Age  Height  Weight
Profession
Student      22      66     140
Teacher      42      70     148
Engineer     30      62     125
Doctor       35      68     160
Nurse        25      62     152

In [14]:
#multi-indexing
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))

In [15]:
print("\nTuple pairs after the zip and list command\n",'-'*45, sep='')
print(hier_index)

Tuple pairs after the zip and list command
---------------------------------------------
[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [24]:
hier_index = pd.MultiIndex.from_tuples(hier_index)
print("\nIndex hierarchy\n",'-'*25, sep='')
print(hier_index)

Index hierarchy
-------------------------
MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [17]:
print("\nIndex hierarchy type\n",'-'*25, sep='')
print(type(hier_index))

Index hierarchy type
-------------------------
<class 'pandas.core.indexes.multi.MultiIndex'>

In [18]:
print("\nCreating DataFrame with multi-index\n",'-'*37, sep='')
#np.random.seed(101)
df1 = pd.DataFrame(data=np.round(rn(6,3)), index= hier_index, columns= ['A','B','C'])
print(df1)

Creating DataFrame with multi-index
-------------------------------------
        A    B    C
G1 1 -1.0 -0.0  1.0
   2  2.0  1.0  1.0
   3  1.0 -2.0  0.0
G2 1 -0.0 -0.0 -1.0
   2  1.0 -0.0 -0.0
   3  1.0 -1.0  1.0

In [91]:
#cross tabulation like pivot table

In [92]:
print("\nGrabbing a cross-section from outer level\n",'-'*45, sep='')
print(df1.xs('G1'))

Grabbing a cross-section from outer level
---------------------------------------------
     A    B    C
1 -0.0  1.0 -0.0
2  2.0 -1.0  0.0
3 -0.0 -0.0  1.0

In [19]:
df1.loc['G1']

     A    B    C
1 -1.0 -0.0  1.0
2  2.0  1.0  1.0
3  1.0 -2.0  0.0

In [22]:
df1.loc['G1'].loc[3,['B','C']]

B   -2.0
C    0.0
Name: 3, dtype: float64

In [26]:
#do it in 5
l1 = ['a','a','a','b','b','b','c','c','c']
l2 = [1,2,3,1,2,3,1,2,3]
l3 = [1,2,3,4,5,6,7,8,9]
l = list(zip(l1,l2,l3))
g = pd.MultiIndex.from_tuples(l)
g

MultiIndex([('a', 1, 1),
            ('a', 2, 2),
            ('a', 3, 3),
            ('b', 1, 4),
            ('b', 2, 5),
            ('b', 3, 6),
            ('c', 1, 7),
            ('c', 2, 8),
            ('c', 3, 9)],
           )

In [27]:
df= pd.DataFrame(data=np.round(rn(9,4)),index=g)
df

         0    1    2    3
a 1 1 -1.0  0.0 -0.0  1.0
  2 2 -1.0  3.0  2.0  1.0
  3 3  0.0 -0.0  0.0 -0.0
b 1 4  1.0 -1.0 -2.0 -0.0
  2 5  1.0 -0.0  1.0 -1.0
  3 6 -1.0  1.0  0.0  1.0
c 1 7 -0.0  1.0  1.0 -1.0
  2 8  1.0 -1.0 -0.0 -0.0
  3 9  0.0 -0.0  1.0  0.0